/* generated by _build/build.py — do not edit */
window.BUILD = "1784731280";
window.DECKS = {
 "main": {
  "label": "The presentation",
  "kind": "core",
  "slides": [
   {
    "id": "01",
    "path": "slides/slide_01.html",
    "title": "Sizing Battery Storage for Energy Independence in Israeli Homes",
    "role": "Cover",
    "links": []
   },
   {
    "id": "02",
    "path": "slides/slide_02.html",
    "title": "What we'll cover today",
    "role": "Agenda",
    "links": []
   },
   {
    "id": "03",
    "path": "slides/slide_03.html",
    "title": "Why residential energy independence — and why in Israel",
    "role": "Framing · background",
    "links": []
   },
   {
    "id": "04",
    "path": "slides/slide_04.html",
    "title": "The research question",
    "role": "Framing · the questions",
    "links": []
   },
   {
    "id": "05",
    "path": "slides/slide_05.html",
    "title": "What the literature already covers",
    "role": "Framing · literature",
    "links": [
     {
      "key": "J",
      "label": "The literature table",
      "kind": "list",
      "target": "J_literature_table"
     }
    ]
   },
   {
    "id": "06",
    "path": "slides/slide_06.html",
    "title": "The gap — and where this study sits",
    "role": "Framing · the gap",
    "links": []
   },
   {
    "id": "07",
    "path": "slides/slide_07.html",
    "title": "What actually runs, hour by hour",
    "role": "Method · the simulation",
    "links": [
     {
      "key": "A",
      "label": "Load profile",
      "kind": "list",
      "target": "A_load_profile"
     },
     {
      "key": "B",
      "label": "Parasitic",
      "kind": "list",
      "target": "B_parasitic"
     },
     {
      "key": "C",
      "label": "Validation",
      "kind": "list",
      "target": "C_simulator_validation"
     },
     {
      "key": "D",
      "label": "PV model",
      "kind": "list",
      "target": "D_physical_model"
     },
     {
      "key": "E",
      "label": "Degradation",
      "kind": "list",
      "target": "E_degradation"
     },
     {
      "key": "F",
      "label": "Economics",
      "kind": "list",
      "target": "F_economics"
     },
     {
      "key": "G",
      "label": "Tariff",
      "kind": "list",
      "target": "G_tou_tariff"
     },
     {
      "key": "H",
      "label": "Wind model",
      "kind": "list",
      "target": "H_wind_model"
     }
    ]
   },
   {
    "id": "08",
    "path": "slides/slide_08.html",
    "title": "One run, and what it returns",
    "role": "Method · one run",
    "links": [
     {
      "key": "C",
      "label": "Simulator validation",
      "kind": "list",
      "target": "C_simulator_validation"
     },
     {
      "key": "F",
      "label": "Economics",
      "kind": "list",
      "target": "F_economics"
     }
    ]
   },
   {
    "id": "09",
    "path": "slides/slide_09.html",
    "title": "System components & configuration space",
    "role": "Method · the system",
    "links": [
     {
      "key": "D",
      "label": "PV model",
      "kind": "list",
      "target": "D_physical_model"
     },
     {
      "key": "H",
      "label": "Wind model",
      "kind": "list",
      "target": "H_wind_model"
     },
     {
      "key": "E",
      "label": "Battery",
      "kind": "list",
      "target": "E_degradation"
     }
    ]
   },
   {
    "id": "10",
    "path": "slides/slide_10.html",
    "title": "Base case + three sensitivity studies",
    "role": "Method · experiment design",
    "links": [
     {
      "key": "I",
      "label": "Experimental design",
      "kind": "list",
      "target": "I_experimental_design"
     },
     {
      "key": "K",
      "label": "The results space",
      "kind": "list",
      "target": "K_results_space"
     }
    ]
   },
   {
    "id": "11",
    "path": "slides/slide_11.html",
    "title": "Degradation — year-9 retention",
    "role": "Method · battery model",
    "links": [
     {
      "key": "E",
      "label": "The degradation model",
      "kind": "list",
      "target": "E_degradation"
     }
    ]
   },
   {
    "id": "12",
    "path": "slides/slide_12.html",
    "title": "Dynamic Time-of-Use (ToU) tariff",
    "role": "Method · tariff",
    "links": [
     {
      "key": "G",
      "label": "The ToU tariff",
      "kind": "list",
      "target": "G_tou_tariff"
     }
    ]
   },
   {
    "id": "13",
    "path": "slides/slide_14.html",
    "title": "PV sets the ceiling",
    "role": "Results · the space",
    "links": [
     {
      "key": "K",
      "label": "The results space",
      "kind": "list",
      "target": "K_results_space"
     }
    ]
   },
   {
    "id": "14a",
    "path": "slides/slide_13a.html",
    "title": "Reading one city — Beer-Sheva",
    "role": "Results · the split",
    "links": [
     {
      "key": "A",
      "label": "Load profile",
      "kind": "list",
      "target": "A_load_profile"
     },
     {
      "key": "B",
      "label": "Parasitic load",
      "kind": "list",
      "target": "B_parasitic"
     }
    ]
   },
   {
    "id": "14b",
    "path": "slides/slide_13b.html",
    "title": "How independent is each city?",
    "role": "Results · where energy comes from",
    "links": [
     {
      "key": "H",
      "label": "Wind model",
      "kind": "list",
      "target": "H_wind_model"
     }
    ]
   },
   {
    "id": "14c",
    "path": "slides/slide_13c.html",
    "title": "Where does the generation go?",
    "role": "Results · where generation goes",
    "links": [
     {
      "key": "K",
      "label": "The results space",
      "kind": "list",
      "target": "K_results_space"
     }
    ]
   },
   {
    "id": "15a",
    "path": "slides/slide_14a.html",
    "title": "The 10–15 kWh zone is robust",
    "role": "Q1 · energy lens",
    "links": [
     {
      "key": "K",
      "label": "The results space",
      "kind": "list",
      "target": "K_results_space"
     }
    ]
   },
   {
    "id": "15b",
    "path": "slides/slide_14b.html",
    "title": "Savings agree — 10–15 kWh",
    "role": "Q1 · money lens",
    "links": [
     {
      "key": "F",
      "label": "Economics",
      "kind": "list",
      "target": "F_economics"
     },
     {
      "key": "G",
      "label": "ToU tariff",
      "kind": "list",
      "target": "G_tou_tariff"
     }
    ]
   },
   {
    "id": "16",
    "path": "slides/slide_15.html",
    "title": "Why the battery adds so little money",
    "role": "Q1 · why the money is small",
    "links": [
     {
      "key": "F",
      "label": "Economics — why no discounting",
      "kind": "list",
      "target": "F_economics"
     },
     {
      "key": "G",
      "label": "ToU tariff",
      "kind": "list",
      "target": "G_tou_tariff"
     }
    ]
   },
   {
    "id": "17",
    "path": "slides/slide_16.html",
    "title": "Four cities — location matters",
    "role": "Q1 · across cities",
    "links": [
     {
      "key": "H",
      "label": "Wind model",
      "kind": "list",
      "target": "H_wind_model"
     }
    ]
   },
   {
    "id": "18",
    "path": "slides/slide_q2_wind.html",
    "title": "Wind vs storage — Haifa and Beer-Sheva",
    "role": "Q2 · wind",
    "links": [
     {
      "key": "H",
      "label": "Wind model",
      "kind": "list",
      "target": "H_wind_model"
     }
    ]
   },
   {
    "id": "19",
    "path": "slides/slide_q3_consumption.html",
    "title": "Three houses × four cities",
    "role": "Q3 · consumption",
    "links": [
     {
      "key": "A",
      "label": "Load profile",
      "kind": "list",
      "target": "A_load_profile"
     }
    ]
   },
   {
    "id": "20",
    "path": "slides/slide_q4_degradation.html",
    "title": "Technical loss, economic non-event",
    "role": "Q4 · degradation",
    "links": [
     {
      "key": "E",
      "label": "The degradation model",
      "kind": "list",
      "target": "E_degradation"
     }
    ]
   },
   {
    "id": "21",
    "path": "slides/slide_18.html",
    "title": "Four questions, four answers",
    "role": "Closing · the answers",
    "links": [
     {
      "key": "K",
      "label": "The results space",
      "kind": "list",
      "target": "K_results_space"
     }
    ]
   },
   {
    "id": "22",
    "path": "slides/slide_19.html",
    "title": "From insights to design rules",
    "role": "Closing · discussion",
    "links": []
   },
   {
    "id": "23",
    "path": "slides/slide_20.html",
    "title": "Limitations & future work",
    "role": "Closing · limitations",
    "links": []
   },
   {
    "id": "24",
    "path": "slides/slide_21.html",
    "title": "Thank you",
    "role": "Closing · conclusion",
    "links": []
   }
  ]
 },
 "A_load_profile": {
  "label": "A · Load profile",
  "kind": "backup",
  "slides": [
   {
    "id": "A_load_profile-1",
    "path": "decks/A_load_profile/s01.html",
    "title": "Slide 1",
    "role": "",
    "links": []
   },
   {
    "id": "A_load_profile-2",
    "path": "decks/A_load_profile/s02.html",
    "title": "A household's use is temperature-driven",
    "role": "",
    "links": []
   },
   {
    "id": "A_load_profile-3",
    "path": "decks/A_load_profile/s03.html",
    "title": "Four intra-day shapes",
    "role": "",
    "links": []
   },
   {
    "id": "A_load_profile-4",
    "path": "decks/A_load_profile/s04.html",
    "title": "Transparent, deterministic rules",
    "role": "",
    "links": []
   },
   {
    "id": "A_load_profile-5",
    "path": "decks/A_load_profile/s05.html",
    "title": "Cooling emphasis & special days",
    "role": "",
    "links": []
   },
   {
    "id": "A_load_profile-6",
    "path": "decks/A_load_profile/s06.html",
    "title": "Beer Sheva vs Haifa",
    "role": "",
    "links": []
   },
   {
    "id": "A_load_profile-7",
    "path": "decks/A_load_profile/s07.html",
    "title": "Dedicated profiles — per region, three levels",
    "role": "",
    "links": []
   },
   {
    "id": "A_load_profile-8",
    "path": "decks/A_load_profile/s08.html",
    "title": "It closes at daily & hourly resolution",
    "role": "",
    "links": []
   },
   {
    "id": "A_load_profile-9",
    "path": "decks/A_load_profile/s09.html",
    "title": "No single “true” profile — transparent & reasonable",
    "role": "",
    "links": []
   }
  ]
 },
 "B_parasitic": {
  "label": "B · Parasitic cooling energy",
  "kind": "backup",
  "slides": [
   {
    "id": "B_parasitic-1",
    "path": "decks/B_parasitic/s01.html",
    "title": "Slide 1",
    "role": "",
    "links": []
   },
   {
    "id": "B_parasitic-2",
    "path": "decks/B_parasitic/s02.html",
    "title": "A battery bank must be actively cooled",
    "role": "",
    "links": []
   },
   {
    "id": "B_parasitic-3",
    "path": "decks/B_parasitic/s03.html",
    "title": "A transparent, deterministic two-term rule",
    "role": "",
    "links": []
   },
   {
    "id": "B_parasitic-4",
    "path": "decks/B_parasitic/s04.html",
    "title": "A flat floor, a summer cooling bulge",
    "role": "",
    "links": []
   },
   {
    "id": "B_parasitic-5",
    "path": "decks/B_parasitic/s05.html",
    "title": "Derived from temperature, not injected",
    "role": "",
    "links": []
   },
   {
    "id": "B_parasitic-6",
    "path": "decks/B_parasitic/s06.html",
    "title": "Present in every one of the 8,760 hours",
    "role": "",
    "links": []
   },
   {
    "id": "B_parasitic-7",
    "path": "decks/B_parasitic/s07.html",
    "title": "A room-cooling load — not a haircut on efficiency",
    "role": "",
    "links": []
   },
   {
    "id": "B_parasitic-8",
    "path": "decks/B_parasitic/s08.html",
    "title": "Every scenario judged against its own load",
    "role": "",
    "links": []
   }
  ]
 },
 "C_simulator_validation": {
  "label": "C · Simulator validation",
  "kind": "backup",
  "slides": [
   {
    "id": "C_simulator_validation-1",
    "path": "decks/C_simulator_validation/s01.html",
    "title": "Slide 1",
    "role": "",
    "links": []
   },
   {
    "id": "C_simulator_validation-2",
    "path": "decks/C_simulator_validation/s02.html",
    "title": "The honest worry — and the two-layer answer",
    "role": "",
    "links": []
   },
   {
    "id": "C_simulator_validation-3",
    "path": "decks/C_simulator_validation/s03.html",
    "title": "Same system & input — for all three engines",
    "role": "",
    "links": []
   },
   {
    "id": "C_simulator_validation-4",
    "path": "decks/C_simulator_validation/s04.html",
    "title": "Every cell compared — engine by engine",
    "role": "",
    "links": []
   },
   {
    "id": "C_simulator_validation-5",
    "path": "decks/C_simulator_validation/s05.html",
    "title": "Annual DC energy — thesis, pvlib & PVWatts",
    "role": "",
    "links": []
   },
   {
    "id": "C_simulator_validation-6",
    "path": "decks/C_simulator_validation/s06.html",
    "title": "Bit-exact database audit",
    "role": "",
    "links": []
   },
   {
    "id": "C_simulator_validation-7",
    "path": "decks/C_simulator_validation/s07.html",
    "title": "Two external engines disagree by the same order — so it's not circular",
    "role": "",
    "links": []
   },
   {
    "id": "C_simulator_validation-8",
    "path": "decks/C_simulator_validation/s08.html",
    "title": "The median barely moves — only the edge max explodes",
    "role": "",
    "links": []
   },
   {
    "id": "C_simulator_validation-9",
    "path": "decks/C_simulator_validation/s09.html",
    "title": "Three different sub-models, each about 1–2%",
    "role": "",
    "links": []
   },
   {
    "id": "C_simulator_validation-10",
    "path": "decks/C_simulator_validation/s10.html",
    "title": "Percentage gaps between engines are the norm — the thesis at the low end",
    "role": "",
    "links": []
   }
  ]
 },
 "D_physical_model": {
  "label": "D · PV physical model",
  "kind": "backup",
  "slides": [
   {
    "id": "D_physical_model-1",
    "path": "decks/D_physical_model/s01.html",
    "title": "Slide 1",
    "role": "",
    "links": []
   },
   {
    "id": "D_physical_model-2",
    "path": "decks/D_physical_model/s02.html",
    "title": "Irradiance → temperature → DC power",
    "role": "",
    "links": []
   },
   {
    "id": "D_physical_model-3",
    "path": "decks/D_physical_model/s03.html",
    "title": "Three sub-models — each worth 1–2%",
    "role": "",
    "links": []
   },
   {
    "id": "D_physical_model-4",
    "path": "decks/D_physical_model/s04.html",
    "title": "The one-to-one check — cell by cell",
    "role": "",
    "links": []
   },
   {
    "id": "D_physical_model-5",
    "path": "decks/D_physical_model/s05.html",
    "title": "Annual DC energy — three engines, four cities",
    "role": "",
    "links": []
   },
   {
    "id": "D_physical_model-6",
    "path": "decks/D_physical_model/s06.html",
    "title": "A few single percent is the norm",
    "role": "",
    "links": []
   },
   {
    "id": "D_physical_model-7",
    "path": "decks/D_physical_model/s07.html",
    "title": "Three separate questions — three answers",
    "role": "",
    "links": []
   }
  ]
 },
 "E_degradation": {
  "label": "E · Battery degradation",
  "kind": "backup",
  "slides": [
   {
    "id": "E_degradation-1",
    "path": "decks/E_degradation/s01.html",
    "title": "Slide 1",
    "role": "",
    "links": []
   },
   {
    "id": "E_degradation-2",
    "path": "decks/E_degradation/s02.html",
    "title": "Battery initialization & hourly update",
    "role": "",
    "links": []
   },
   {
    "id": "E_degradation-3",
    "path": "decks/E_degradation/s03.html",
    "title": "Nominal vs usable — geometric, not linear",
    "role": "",
    "links": []
   },
   {
    "id": "E_degradation-4",
    "path": "decks/E_degradation/s04.html",
    "title": "Year-0 invariance — imports & exports",
    "role": "",
    "links": []
   },
   {
    "id": "E_degradation-5",
    "path": "decks/E_degradation/s05.html",
    "title": "Year-0 invariance — savings & net bill",
    "role": "",
    "links": []
   },
   {
    "id": "E_degradation-6",
    "path": "decks/E_degradation/s06.html",
    "title": "Decade evolution — independence & savings",
    "role": "",
    "links": []
   },
   {
    "id": "E_degradation-7",
    "path": "decks/E_degradation/s07.html",
    "title": "Decade evolution — grid imports & exports",
    "role": "",
    "links": []
   },
   {
    "id": "E_degradation-8",
    "path": "decks/E_degradation/s08.html",
    "title": "Performance — 60 m² PV, 20 kWh battery",
    "role": "",
    "links": []
   },
   {
    "id": "E_degradation-9",
    "path": "decks/E_degradation/s09.html",
    "title": "What changes over a decade — and by how much",
    "role": "",
    "links": []
   },
   {
    "id": "E_degradation-10",
    "path": "decks/E_degradation/s10.html",
    "title": "Effective rates, benchmark & caveats",
    "role": "",
    "links": []
   }
  ]
 },
 "F_economics": {
  "label": "F · Economics",
  "kind": "backup",
  "slides": [
   {
    "id": "F_economics-1",
    "path": "decks/F_economics/s01.html",
    "title": "Slide 1",
    "role": "",
    "links": []
   },
   {
    "id": "F_economics-2",
    "path": "decks/F_economics/s02.html",
    "title": "A static, present-day snapshot",
    "role": "",
    "links": []
   },
   {
    "id": "F_economics-3",
    "path": "decks/F_economics/s03.html",
    "title": "Battery-storage cost vs capacity",
    "role": "",
    "links": []
   },
   {
    "id": "F_economics-4",
    "path": "decks/F_economics/s04.html",
    "title": "What the battery itself adds — and why it never pays back",
    "role": "",
    "links": []
   },
   {
    "id": "F_economics-5",
    "path": "decks/F_economics/s05.html",
    "title": "Why the marginal saving is small",
    "role": "",
    "links": []
   },
   {
    "id": "F_economics-6",
    "path": "decks/F_economics/s06.html",
    "title": "Why discounting was not applied",
    "role": "",
    "links": []
   },
   {
    "id": "F_economics-7",
    "path": "decks/F_economics/s07.html",
    "title": "A resilience expenditure, not an investment",
    "role": "",
    "links": []
   }
  ]
 },
 "G_tou_tariff": {
  "label": "G · Time-of-use tariff",
  "kind": "backup",
  "slides": [
   {
    "id": "G_tou_tariff-1",
    "path": "decks/G_tou_tariff/s01.html",
    "title": "Slide 1",
    "role": "",
    "links": []
   },
   {
    "id": "G_tou_tariff-2",
    "path": "decks/G_tou_tariff/s02.html",
    "title": "Purchase tariff — weekdays",
    "role": "",
    "links": []
   },
   {
    "id": "G_tou_tariff-3",
    "path": "decks/G_tou_tariff/s03.html",
    "title": "Weekend & holiday tariff",
    "role": "",
    "links": []
   },
   {
    "id": "G_tou_tariff-4",
    "path": "decks/G_tou_tariff/s04.html",
    "title": "Feed-in, dispatch & metrics",
    "role": "",
    "links": []
   },
   {
    "id": "G_tou_tariff-5",
    "path": "decks/G_tou_tariff/s05.html",
    "title": "The band spread — what drives every result",
    "role": "",
    "links": []
   }
  ]
 },
 "H_wind_model": {
  "label": "H · Wind model",
  "kind": "backup",
  "slides": [
   {
    "id": "H_wind_model-1",
    "path": "decks/H_wind_model/s01.html",
    "title": "Slide 1",
    "role": "",
    "links": []
   },
   {
    "id": "H_wind_model-2",
    "path": "decks/H_wind_model/s02.html",
    "title": "The wind model and the power curve",
    "role": "",
    "links": []
   },
   {
    "id": "H_wind_model-3",
    "path": "decks/H_wind_model/s03.html",
    "title": "Annual per-turbine yield & its share",
    "role": "",
    "links": []
   },
   {
    "id": "H_wind_model-4",
    "path": "decks/H_wind_model/s04.html",
    "title": "Turbine counts per city",
    "role": "",
    "links": []
   },
   {
    "id": "H_wind_model-5",
    "path": "decks/H_wind_model/s05.html",
    "title": "Independence, savings & value per turbine",
    "role": "",
    "links": []
   },
   {
    "id": "H_wind_model-6",
    "path": "decks/H_wind_model/s06.html",
    "title": "Storage amplifies the wind contribution",
    "role": "",
    "links": []
   },
   {
    "id": "H_wind_model-7",
    "path": "decks/H_wind_model/s07.html",
    "title": "When wind becomes dominant",
    "role": "",
    "links": []
   },
   {
    "id": "H_wind_model-8",
    "path": "decks/H_wind_model/s08.html",
    "title": "Limitations and design recommendations",
    "role": "",
    "links": []
   }
  ]
 },
 "I_experimental_design": {
  "label": "I · Experimental design",
  "kind": "backup",
  "slides": [
   {
    "id": "I_experimental_design-1",
    "path": "decks/I_experimental_design/s01.html",
    "title": "Slide 1",
    "role": "",
    "links": []
   },
   {
    "id": "I_experimental_design-2",
    "path": "decks/I_experimental_design/s02.html",
    "title": "Base Case — 80 runs",
    "role": "",
    "links": []
   },
   {
    "id": "I_experimental_design-3",
    "path": "decks/I_experimental_design/s03.html",
    "title": "Wind Turbines — 120 runs",
    "role": "",
    "links": []
   },
   {
    "id": "I_experimental_design-4",
    "path": "decks/I_experimental_design/s04.html",
    "title": "Consumption Profile — 240 runs",
    "role": "",
    "links": []
   },
   {
    "id": "I_experimental_design-5",
    "path": "decks/I_experimental_design/s05.html",
    "title": "Battery Degradation — 60 runs",
    "role": "",
    "links": []
   },
   {
    "id": "I_experimental_design-6",
    "path": "decks/I_experimental_design/s06.html",
    "title": "500 Runs — One Variable at a Time",
    "role": "",
    "links": []
   }
  ]
 },
 "J_literature_table": {
  "label": "J · Literature comparison",
  "kind": "backup",
  "slides": [
   {
    "id": "J_literature_table-1",
    "path": "decks/J_literature_table/s01.html",
    "title": "Slide 1",
    "role": "",
    "links": []
   },
   {
    "id": "J_literature_table-2",
    "path": "decks/J_literature_table/s02.html",
    "title": "Five criteria — tick or nothing",
    "role": "",
    "links": []
   },
   {
    "id": "J_literature_table-3",
    "path": "decks/J_literature_table/s03.html",
    "title": "One row has five ticks",
    "role": "",
    "links": []
   },
   {
    "id": "J_literature_table-4",
    "path": "decks/J_literature_table/s04.html",
    "title": "Two Israeli studies — neither is a home",
    "role": "",
    "links": []
   },
   {
    "id": "J_literature_table-5",
    "path": "decks/J_literature_table/s05.html",
    "title": "Out of fifteen studies",
    "role": "",
    "links": []
   },
   {
    "id": "J_literature_table-6",
    "path": "decks/J_literature_table/s06.html",
    "title": "Already written in the thesis",
    "role": "",
    "links": []
   }
  ]
 },
 "K_results_space": {
  "label": "K · The results space",
  "kind": "backup",
  "slides": [
   {
    "id": "K_results_space-1",
    "path": "decks/K_results_space/s01.html",
    "title": "Slide 1",
    "role": "",
    "links": []
   },
   {
    "id": "K_results_space-2",
    "path": "decks/K_results_space/s02.html",
    "title": "Jump to any chart",
    "role": "",
    "links": []
   },
   {
    "id": "K_results_space-3",
    "path": "decks/K_results_space/s03.html",
    "title": "Beer-Sheva — Consumption sweep",
    "role": "",
    "links": []
   },
   {
    "id": "K_results_space-4",
    "path": "decks/K_results_space/s04.html",
    "title": "Beer-Sheva — PV area sweep",
    "role": "",
    "links": []
   },
   {
    "id": "K_results_space-5",
    "path": "decks/K_results_space/s05.html",
    "title": "Beer-Sheva — Battery sweep",
    "role": "",
    "links": []
   },
   {
    "id": "K_results_space-6",
    "path": "decks/K_results_space/s06.html",
    "title": "Beer-Sheva — Turbines sweep",
    "role": "",
    "links": []
   },
   {
    "id": "K_results_space-7",
    "path": "decks/K_results_space/s07.html",
    "title": "Jerusalem — Consumption sweep",
    "role": "",
    "links": []
   },
   {
    "id": "K_results_space-8",
    "path": "decks/K_results_space/s08.html",
    "title": "Jerusalem — PV area sweep",
    "role": "",
    "links": []
   },
   {
    "id": "K_results_space-9",
    "path": "decks/K_results_space/s09.html",
    "title": "Jerusalem — Battery sweep",
    "role": "",
    "links": []
   },
   {
    "id": "K_results_space-10",
    "path": "decks/K_results_space/s10.html",
    "title": "Jerusalem — Turbines sweep",
    "role": "",
    "links": []
   },
   {
    "id": "K_results_space-11",
    "path": "decks/K_results_space/s11.html",
    "title": "Tel Aviv — Consumption sweep",
    "role": "",
    "links": []
   },
   {
    "id": "K_results_space-12",
    "path": "decks/K_results_space/s12.html",
    "title": "Tel Aviv — PV area sweep",
    "role": "",
    "links": []
   },
   {
    "id": "K_results_space-13",
    "path": "decks/K_results_space/s13.html",
    "title": "Tel Aviv — Battery sweep",
    "role": "",
    "links": []
   },
   {
    "id": "K_results_space-14",
    "path": "decks/K_results_space/s14.html",
    "title": "Tel Aviv — Turbines sweep",
    "role": "",
    "links": []
   },
   {
    "id": "K_results_space-15",
    "path": "decks/K_results_space/s15.html",
    "title": "Haifa — Consumption sweep",
    "role": "",
    "links": []
   },
   {
    "id": "K_results_space-16",
    "path": "decks/K_results_space/s16.html",
    "title": "Haifa — PV area sweep",
    "role": "",
    "links": []
   },
   {
    "id": "K_results_space-17",
    "path": "decks/K_results_space/s17.html",
    "title": "Haifa — Battery sweep",
    "role": "",
    "links": []
   },
   {
    "id": "K_results_space-18",
    "path": "decks/K_results_space/s18.html",
    "title": "Haifa — Turbines sweep",
    "role": "",
    "links": []
   }
  ]
 }
};
